on: 
  push:
    branches:
      - main
name: Deploy website on push
jobs:
  web-deploy:
    name: main
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish Podosys.Worker.Api/Podosys.Worker.Api.csproj -c Release /p:EnvironmentName=Production --output ./publish 
  
    - name: Deploy to PRD
      uses: jahbenjah/SmarterASP.NET-web-deploy@1.0.0.alpha.8
      with:
        website-name: fernandogouvea-001-site2
        server-computer-name: https://win5055.site4now.net:8172
        server-username: fernandogouvea-001
        server-password: Tx7807801313*

        #teste